title: Ravi Dave
email: ravi.dave@curiousatom.tech
description: "Sharing data engineering, analytics and learning notes."
baseurl: "" # change if hosted at /repo-name
url: "https://curiousravi.github.io" # update after creating repo
theme: null
